#!/usr/bin/python3
MyList = __import__('1-my_list').MyList

lst = MyList()
my_list = MyList()
my_list.append(1)
my_list.append(4)
my_list.append(2)
my_list.append(3)
my_list.append(5)
ng = MyList()
ng.append(-1)
ng.append(-9)
ng.append(-6)
ng.append(-3)
ng.append(-4)
ng.append(-8)
ng.append(-7)
print(my_list)
my_list.print_sorted()
print(my_list)
print(ng)
ng.print_sorted()
print(ng)
empt = MyList()
print(empt)
